### ISSUE TITLE
? Move the controls (fullscreen, mute, state) to upper right corner (share?)

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#1009]
Spinner and arrows remain in lower right

**Comment by dannydb** [comment]
This is going to mean major surgery for the boards:

![screen shot 2014-10-30 at 10 22 52 am](https://cloud.githubusercontent.com/assets/419297/4844901/4bccd6e4-6040-11e4-914c-29ebf8b49a73.png)

/cc @onyxfish @brianboyer
