### ISSUE TITLE
Scoredboard results should be sorted vertically first, not horizontally (columnized)

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#1049]

**Comment by onyxfish** [comment]
@xtinarees Might be good to pair with @eads on this. He is working on other columnizer stuff.

**Comment by eads** [comment]
@xtinarees I found the solution! 

The trick is to use the `range` function and slice syntax. `range(start, stop, step_size)` spits out numbers from start to (stop - 1), advancing step_size numbers on each iteration. 

```
def columnize_card(races, columns):
    results = []
    if len(races):
        columns = float(columns)
        rows = ceil(len(races)/columns)
        rows = int(rows)
        for i in range(0, len(races), rows):
            results.append(races[i:i+rows])

    return results
```

Closed -- implementing for all scorecards is the next task (see #1147).
