### ISSUE TITLE
Verify all daemons are working on production server before we go live

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#1081]
Check logs. Make sure slides, previews, boards, etc are all deployed. Verify pre-launch live blog posts are synced up and that stack.json exists.

**Comment by eads** [comment]
The results daemon is definitely working -- cranking along. The liveblog is shakier but just on prod, I suspect because of the cutoff (cuton?) time.

**Comment by eads** [comment]
It was the tumblr configuration variables, it would seem. I changed them on prod and ran the daemon and it generated the slides (which I cleared out of S3). We'll want to keep a keen eye on the liveblog deployment when we get started.

**Comment by eads** [comment]
(I think I'll leave this open til content and results start flowing in)
