### ISSUE TITLE
need to notify the user that we chose a state for you, and you can change it

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#1139]
and instead put a prompt somewhere that says -- we guessed that you're in DC, use the controls to pick another state -- maybe a little growl, or a note on the state results page.

**Comment by brianboyer** [comment]
or maybe the state on the front page is a good way to draw people in. hrm.

**Comment by brianboyer** [comment]
yep. let's do this. the welcome screen is trying to do too much, and we shouldn't go back to a second state-picker step.

**Comment by brianboyer** [comment]
and if we can't geoip a state, just pick one

**Comment by onyxfish** [comment]
I like the idea of just picking with an interesting default. Not sure how we should communicate this to the user, though?

**Comment by brianboyer** [comment]
Yeah, I was thinking that it would show up on the state slide. Dunno. But I
_really_ like streamlining the welcome screen.

**Comment by brianboyer** [comment]
hmmmmmmm nope.
