### ISSUE TITLE
it annoys me that when i click on our controls, the element gets highlighted

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#1165]
there's gotta be a way to make this not happen, right?
![screen shot 2014-11-01 at 9 30 06 pm](https://cloud.githubusercontent.com/assets/68644/4873937/dafe6616-622f-11e4-8d2e-1b153d9be86e.png)
![screen shot 2014-11-01 at 9 30 01 pm](https://cloud.githubusercontent.com/assets/68644/4873938/dcdff846-622f-11e4-8b5e-644321699512.png)

**Comment by onyxfish** [comment]
There is. I know Danny knows the trick.

**Comment by alykat** [comment]
New mixin: `.unselectable` — adds `user-select: none;` css classes.
