### ISSUE TITLE
Site doesn't work outside the US

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#1205]

**Comment by onyxfish** [comment]
I just Tor'ed through from the Netherlands and it seems to have defaulted the geoip to CA, which is the correct behavior. The site was broken in other ways that I'm attributing to Tor.

**Comment by onyxfish** [comment]
@eads I buttoned this up. You want to double-check with Mago if this is working for her now?

**Comment by eads** [comment]
Will do. I tested later last night on Screenhero and Mago's console was showing requests for state slides suffixed with `-NLE`.
