### ISSUE TITLE
IE: Bottom nav broken 

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#1229]
![screen shot 2014-11-03 at 10 20 26 am](https://cloud.githubusercontent.com/assets/1077075/4884564/f1595004-636c-11e4-9bd3-56a0b7791401.png)

**Comment by onyxfish** [comment]
Retest and add new screenshot if still broken

**Comment by TylerFisher** [comment]
Yup, still broken 
![screen shot 2014-11-03 at 5 30 29 pm](https://cloud.githubusercontent.com/assets/1077075/4891534/f7c0f83e-63a8-11e4-8c34-08a4c1c30ce4.png)
