### ISSUE TITLE
Android: multiple display bugs

### ISSUE THREAD

**Issue by lindamood** [nprapps/elections14#1244]
Ugh, sorry for the weird orientation on these photos. 

![img_1041](https://cloud.githubusercontent.com/assets/1319852/4886413/fe25bebc-637b-11e4-9810-fb3decfea4b1.JPG)

![img_1040](https://cloud.githubusercontent.com/assets/1319852/4886346/8884e73c-637b-11e4-8422-d3a28a951448.JPG)

![img_1039](https://cloud.githubusercontent.com/assets/1319852/4886466/676fe9ce-637c-11e4-9bbe-cc98ccd5d9b6.JPG)

**Comment by onyxfish** [comment]
Confirmed that android is super busted.

**Comment by onyxfish** [comment]
See granular tickets
