### ISSUE TITLE
Compress promo.mp3 better

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#1332]
My naive attempt turned 600kb `www/assets/promo_original.wav` into 150kb `www/assets/promo.mp3`. I'm sure it's possible to do better.

**Comment by TylerFisher** [comment]
Pushed `www/assets/promo_compressed.mp3` to the assets rig. Down to 75kb with variable bitrate between 65kbps and 105kbps + mono channel. Can get lower, but it starts to sound pretty artifacty.
