### ISSUE TITLE
Looks like we've gotta nudge the source line again

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#1334]
![screen shot 2014-11-03 at 10 33 33 pm](https://cloud.githubusercontent.com/assets/68644/4894470/68d87b9e-63d3-11e4-9a07-633659b68113.png)

**Comment by onyxfish** [comment]
![img_2247](https://cloud.githubusercontent.com/assets/33046/4905588/61ca560a-6451-11e4-9ae2-476229da2893.JPG)
