### ISSUE TITLE
how concerned should I be that the BOP numbers are very different?

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#1337]
![screen shot 2014-11-04 at 6 45 29 am](https://cloud.githubusercontent.com/assets/68644/4899122/8adbecea-6418-11e4-846a-97902e2f7eef.png)

**Comment by onyxfish** [comment]
BOP in the footer appears to be incorrect on page load, but then corrects itself on first refresh. My guess is we're not rerendering index.html when we rerender the slides (or not redeploying it). The expedient fix is to not bootstrap that data onto the page.

**Comment by eads** [comment]
@onyxfish I just checked and that appears to be the issue. Or we can re-render index.html periodically.

**Comment by onyxfish** [comment]
@eads I'm going to remove the bootstrapped data for now and make a lower-priority ticket to fix it more better.

**Comment by onyxfish** [comment]
@eads Eh, actually it sort of fucks up the layout to fix it this way. We probably need to fix it right and rerender index.html.

**Comment by onyxfish** [comment]
Fixed.
