### ISSUE TITLE
Charlie's ballot measure edits add some line breaks

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#1339]

**Comment by dannydb** [comment]
Three options:
1. More copy editing to reduce the length of the descriptions.
2. Tiny, borderline unreadable text
3. Allow the line-breaking as gracefully as we can.

Here are screen captures of 2 & 3:

![screen shot 2014-11-04 at 10 46 31 am](https://cloud.githubusercontent.com/assets/419297/4902564/1e42958a-643a-11e4-8103-a5c255dcaa0a.png)

![screen shot 2014-11-04 at 10 48 04 am](https://cloud.githubusercontent.com/assets/419297/4902568/2177f326-643a-11e4-9a0d-ad75a77ab985.png)

**Comment by eads** [comment]
I like the graceful line breaking, personally. Also, paging @brianboyer what about changing "For"/"against" to "yes"/"no" -- those columns could be much narrower. The "for/again" language is from the AP data/ballot description.

**Comment by onyxfish** [comment]
@brianboyer Weigh in?

**Comment by brianboyer** [comment]
yep, let 'em wrap.
