### ISSUE TITLE
what things should late shift be monitoring?

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#1346]

**Comment by eads** [comment]
- Chartbeat
- Google analytics
- deploy_results.log
- deploy_liveblog.log
- Cloudfront reports (https://console.aws.amazon.com/cloudfront/home?region=us-east-1#usage_reports:)
- Twitter
- Facebook

**Comment by onyxfish** [comment]
Top on production!

**Comment by onyxfish** [comment]
The Slack channel. Jake invited two AP devs to join it.
