### ISSUE TITLE
Hitting index yields IOError for www/live-data/init.json

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#136]
`IOError: [Errno 2] No such file or directory: 'www/live-data/init.json'`

**Comment by onyxfish** [comment]
data.bootstrap should create this?

**Comment by TylerFisher** [comment]
data.update does, though maybe bootstrap should

**Comment by onyxfish** [comment]
Well docs currently say to run them both, but it might be worth revisiting that just for convenience.

**Comment by eads** [comment]
Running 'fab data.update` doesn't resolve the issue for me.
