### ISSUE TITLE
Vertically center state results

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#1365]
I thought I did this and yet...

![img_2248](https://cloud.githubusercontent.com/assets/33046/4905593/6e51136e-6451-11e4-8a8c-ffab9c0d781b.JPG)

**Comment by dannydb** [comment]
Not seeing this locally:

![screen shot 2014-11-04 at 1 51 55 pm](https://cloud.githubusercontent.com/assets/419297/4905837/b3187f4e-6453-11e4-941d-8ae8a4cdcb31.png)
