### ISSUE TITLE
Browser testing: Desktop Safari

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#14]

**Comment by lindamood** [comment]
Tested in safari/mac Version 7.0.6. I have screenshots if you want them.
- Responds to viewport size changes / device rotation- yes, but doesn't fill screen of large viewport.

![elections_2014](https://cloud.githubusercontent.com/assets/1319852/4866384/594ef806-612b-11e4-8985-8da86cc5de61.png)
- Countdown display animates correctly- yes, but getting cut off at some viewport sizes.

![elections_2014 copy](https://cloud.githubusercontent.com/assets/1319852/4866371/52028a72-612b-11e4-80f2-646d5c87e33f.png)
- All slides fit the layout-- Ohio Governors big board getting cut off in full screen mode
- Newly selected state is displayed- selection of another state doesn't work.

![screenshot_10_31_14__1_29_pm](https://cloud.githubusercontent.com/assets/1319852/4866388/600f56d6-612b-11e4-833a-e8a1212cf98e.png)
