### ISSUE TITLE
Device testing: iPhone Chrome/Webkit

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#16]

**Comment by lindamood** [comment]
Bugs are bolded

1 Responds to viewport size changes / device rotation- yes
2 State seletbox works- yes
3 Newly selected state is displayed- yes
4 Displays "Come on In" button and Chromecast badge on non-Chromecasting devices- yes
5 Displays "Chromecast now" button on Chromecasting devices-**yes, but the button doesn't do anything**
6 Selected state carries over to stack- N/A
7 Countdown works- yes
8 Countdown display animates correctly- **yes, but you can't see it in landscape mode until you scroll down**
9 All slides fit the layout- **no, source line and nav are getting cut off**
10 Slides reduce to fit the viewport without breaking out of 16:9 aspect ratio- yes
11 Audio plays- yes
12 Mute/unmute button works-yes
13 Fullscreen button works- n/a
14 State is correctly displayed- yes
15 State change button launches state change screen- N/A
16 Back button reloads previous slide and resets slide advance timer- yes
17 Next button loads next slide and resets slide advance timer- yes
18 Slide advance countdown works- yes
19 Slide advance countdown animates correctly-yes
20 Senate BOP of power is hidden in footer when a BOP is present on another slide (House BB, Senate BB, BOP charts)- **no, senate BOP is persistent across all slides**
State change screen (N/A- feature has been removed):
22 Select state is carried over from stack
23 Typeahead works
24 Newly selected state is displayed
25 "Go" button returns to stack
Chromecast remote: (didn't test)
26 Is displayed when casting
27 Is displayed when connecting to an existing cast session
28 Mute/unmute button works
29 Select state button shows state change screen
30 Stop casting button ends session
