### ISSUE TITLE
Device testing: iPad

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#17]

**Comment by lindamood** [comment]
- Responds to viewport size changes / device rotation- Initially the screen was blank. when I rotated it remained blank. Then I refreshed and the intro screen showed up, so it may have just been a glitch.
  ![img_1034](https://cloud.githubusercontent.com/assets/1319852/4866786/2ca0b80e-612f-11e4-8d97-f5d103236574.JPG)
- State selection typeahead works- kind of- you can't tap on the name of the state in the typeahead menu. you need to type the full name of the state and then hit the go button on the iOS keyboard. Tapping "Go" on the iOS keyboard without typing the full state name takes me somewhere, but I'm not sure where. The state name is not yet visible on the slides in iOS.
  
  **I stopped testing this after the welcome screen. Seems like things are still in progress on mobile, so I can test more later.**

**Comment by lindamood** [comment]
Welcome screen:
1 Responds to viewport size changes / device rotation- yes
2 State selectbox works- yes
3 Newly selected state is displayed- yes
4 Displays "Come on In" button and Chromecast badge on non-Chromecasting devices- yes
5 Displays "Chromecast now" button on Chromecasting devices- yes
6 Selected state carries over to stack- N/A

Countdown screen:
7 Countdown works- yes
8 Countdown display animates correctly- yes

Stack:
9 All slides fit the layout- yes
10 Slides reduce to fit the viewport without breaking out of 16:9 aspect ratio- yes
11 Audio plays- yes
12 Mute/unmute button works- yes
13 Fullscreen button works- n/a
14 State is correctly displayed- yes
15 State change button launches state change screen- N/A
**16 Back button reloads previous slide and resets slide advance timer- no slide forward back buttons do not currently work**
**17 Next button loads next slide and resets slide advance timer** 
18 Slide advance countdown works- yes
19 Slide advance countdown animates correctly- yes
**20 Senate BOP of power is hidden in footer when a BOP is present on another slide (House BB, Senate BB, BOP charts)- no, BOP in footer is persistent.**
21 Ensure slides with columns lay out correctly- yes
