### ISSUE TITLE
What if we edit/delete a post in the liveblog?

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#236]

**Comment by onyxfish** [comment]
Currently: deletes and edits both change the id of the post, so they will cause the entire top "page" of posts to be inserted at the top of the live blog, even if they already exist.

**Comment by onyxfish** [comment]
Marking this blocked so we can discuss if it's an issue we need to fix.

**Comment by onyxfish** [comment]
Superseded by #342 and #343
