### ISSUE TITLE
Have good AP data on hand for demo

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#244]
Even if the API is sucking

**Comment by onyxfish** [comment]
We've got mocks now!

**Comment by eads** [comment]
Jaja, there's a bit more to do on this!

**Comment by onyxfish** [comment]
![why-is-this-walrus-so-embarrassed-16271-1300202505-10](https://cloud.githubusercontent.com/assets/33046/4378929/5d4354c6-435c-11e4-9d64-f5fbfa97a458.jpg)
