### ISSUE TITLE
Byline for visuals team

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#27]

**Comment by onyxfish** [comment]
Are we going to try to do this?

**Comment by brianboyer** [comment]
Oh yeah, um, crap. Maybe there's a little icon on the homepage? With the
date published, and credits.

**Comment by brianboyer** [comment]
Let's put it on the welcome screen, at the bottom, in small type.

Design and development by Danny DeBelius, David Eads, Tyler Fisher, Chris Groskopf, Alyson Hurt, Christina Rees and Nick Whitmoyer

Published November 4, 2014
