### ISSUE TITLE
Make big board design work on internet explorer

### ISSUE THREAD

**Issue by xtinarees** [nprapps/elections14#301]

**Comment by xtinarees** [comment]
showing iphone version on desktop :(

**Comment by xtinarees** [comment]
computers in studio have ie 8, which doesn't support media queries

**Comment by alykat** [comment]
I wonder if we can ask IT to update those...

**Comment by onyxfish** [comment]
Email out to IT.

**Comment by onyxfish** [comment]
IT says Chrome is now installed on these boxes. @xtinarees can you check this is done, please?

**Comment by xtinarees** [comment]
Yes, it's done. Chrome is on the studio computers.
