### ISSUE TITLE
Nail down our promotion strategy/schedule

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#321]

**Comment by onyxfish** [comment]
Emailed Brian to figure out how to approach this.

**Comment by onyxfish** [comment]
Meeting invite sent.

**Comment by brianboyer** [comment]
nick is working on a pre-election page and messaging, i'll keep emailing the washington desk, gonna call this closed though

**Comment by brianboyer** [comment]
naw, it should stay open.
