### ISSUE TITLE
Make streaming estimates

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#341]
We need to estimate our peak concurrent sessions and total unique sessions, to make sure we've got enough juice behind the live audio stream. Put together a good guess and send it to Michael Dube.

**Comment by onyxfish** [comment]
Email sent.

**Comment by onyxfish** [comment]
Sent followup nag.

**Comment by onyxfish** [comment]
Michael says we have to specify a number to provision from the CDN, it won't scale up gracefully. Currently set at 50k, but we should talk about what number we actually want to request.

**Comment by onyxfish** [comment]
Email sent requesting we provision for 150k.

**Comment by onyxfish** [comment]
Waiting for Michael to send us the "costs associated".

**Comment by onyxfish** [comment]
Still waiting on prices for Limelight. Sent nag.

**Comment by onyxfish** [comment]
See #832, but otherwise they promised the capacity we need.
