### ISSUE TITLE
Detect user's location and guess their state

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#355]

**Comment by eads** [comment]
Seems like our best options are either the [MaxMind API](https://www.maxmind.com/en/geoip2-precision-city) which is $300 for 750,000 queries or the [HTML5 geo API](http://html5demos.com/geo).

Both have upsides and downsides -- MaxMind doesn't work so great with corporate networks (I'm not sure how the HTML5 fares in comparison, but seems likely to be accurate in more scenarios), the HTML5 api requires the user to allow their location data to be shared.

@onyxfish @nickwhitmoyer @xtinarees the goal here is to pre-fill the state, correct? As opposed to eliminating it completely.

**Comment by eads** [comment]
Excuse me, my cold is clouding my brain -- we'll need to use a geolocation or boundary service in conjunction with the HTML5 api.

**Comment by eads** [comment]
I talked with Brian about this -- locating based on IP address has the nice upside of not requiring any user intervention at all. I've applied for a Maxmind developer demo account to try out their service.

**Comment by eads** [comment]
Rollin' with MaxMind.
