### ISSUE TITLE
Kill any events on a slide after the slide is removed on a page

### ISSUE THREAD

**Issue by alykat** [nprapps/elections14#364]
Example: window.onresize events on d3 slides

**Comment by onyxfish** [comment]
https://api.jquery.com/off/

**Comment by onyxfish** [comment]
Figuring out exactly where this code runs may be tricky. Let's talk about it.

**Comment by alykat** [comment]
I'm not getting console errors anymore (at least in Chrome), so hopefully this isn't as urgent as it was before.

**Comment by TylerFisher** [comment]
I don't think this matters anymore because we're inlining all the JS and removing it from the page when a slide leaves.

**Comment by onyxfish** [comment]
We still need to unwind any events or they will continue to consume memory, which is a problem when this thing is gonna run all night.
