### ISSUE TITLE
Pym error onresize after Senate board slide cycles through

### ISSUE THREAD

**Issue by alykat** [nprapps/elections14#367]
![image](https://cloud.githubusercontent.com/assets/491318/4511841/9584ce20-4b39-11e4-9139-f4bb758b8d92.png)

**Comment by TylerFisher** [comment]
Related to #364 I imagine.

**Comment by onyxfish** [comment]
Still an issue?

**Comment by TylerFisher** [comment]
Pym is totally gone.
