### ISSUE TITLE
Make sure our code handles runoffs correctly

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#386]

**Comment by eads** [comment]
I talked with Charlie -- Lousiana _could_ have a runoff and ergo multiple winners in it's senate race, though I think we could just leave the race unstyled in the big board.

**Comment by eads** [comment]
cc @nickwhitmoyer @xtinarees -- should we indicate runoffs somehow on the big board?

**Comment by eads** [comment]
whoops, not true -- just with API, still need FTP
