### ISSUE TITLE
Poll closing slide: When do polls count as "closed" in a state?

### ISSUE THREAD

**Issue by alykat** [nprapps/elections14#390]
Looking at AP's 2012 closing time spreadsheet, it looks like there are a few cases (in states that span multiple time zones) where results might start to be reported from one half of the state while polls are still open in the other half.

https://www.dropbox.com/s/gizeqpszqt74o7n/2012%20GE%20AP%20Poll%20Hours%20Report.xls?dl=0

Better to count the poll closing time when we're most likely to start getting results? Or the latest poll closing time in the state?

**Comment by eads** [comment]
I talked with Charlie about this. The editorial call is to roll with the latest poll closing time.
