### ISSUE TITLE
Rematches slide: Ask Charlie for a one-line description for each race

### ISSUE THREAD

**Issue by alykat** [nprapps/elections14#410]

**Comment by alykat** [comment]
Email sent

**Comment by onyxfish** [comment]
@eads Are we still waiting for this?

**Comment by eads** [comment]
@onyxfish as far as I know... I don't know much about this ticket.

**Comment by eads** [comment]
I talked with Charlie, he's gonna fwd me the stuff he sent Aly.

**Comment by eads** [comment]
As of late Friday this is no longer blocked.
