### ISSUE TITLE
Verify none of the races we care about can have multiple winners

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#415]
What about ballot initiatives?

**Comment by eads** [comment]
It appears we have 100% pick-1 races with no possibility of multiple winners. The best source I can find on ballot measures is [Ballotpedia's guide](http://ballotpedia.org/Ballot_Measure_Scorecard,_2014#November_4) -- I've directly looked at about half of them (the other half being amendments and other obviously yes/no measures), they're all yes/no.
