### ISSUE TITLE
Fullscreen mode kills the background color

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#429]
![screen shot 2014-10-08 at 12 43 44 pm](https://cloud.githubusercontent.com/assets/1077075/4563043/0438a354-4f0a-11e4-921e-c3fa2e8a3ff1.png)

**Comment by dannydb** [comment]
Still seeing this. 

![screen shot 2014-10-27 at 3 20 06 pm](https://cloud.githubusercontent.com/assets/419297/4797808/78ade466-5e0e-11e4-8a67-eca55e1ecb88.png)
