### ISSUE TITLE
Test big board changes with the hosts

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#430]

**Comment by onyxfish** [comment]
Blocked by #446.

**Comment by eads** [comment]
Scheduled for next Weds.

**Comment by eads** [comment]
We tested with Evie today but the hosts didn't show up. Moving to iteration 6.

**Comment by eads** [comment]
Rescheduled for Thursday

**Comment by eads** [comment]
Had a short meeting today, we'll have another next week.
