### ISSUE TITLE
Sketching: chromecast UI/UX

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#451]
One big question: does Chromecasting change the "select your state" experience

**Comment by onyxfish** [comment]
Opened specific tickets, although I think this is mostly up to us since our app doesn't really fit their model.

**Comment by onyxfish** [comment]
Doh, I closed the wrong ticket. Should have been #105.

**Comment by whitmoyer** [comment]
Here's something I was thinking for a Chromecast menu
https://www.dropbox.com/s/sfs3nbthroax0ky/11.png?dl=0

**Comment by onyxfish** [comment]
See #532.
