### ISSUE TITLE
Write guidebook for DJing the site

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#469]

**Comment by onyxfish** [comment]
Need the slide management tool before I can do much with this. Pushing out of this iteration.

**Comment by onyxfish** [comment]
Meeting request out to Amita.

**Comment by onyxfish** [comment]
Drafted, need to clean it up and run it past @brianboyer: https://docs.google.com/document/d/1uXAtbvDITL2M75kBpSea4Es2jwomRJYl0EQ3Of71VG8/edit#heading=h.j2xf089d4e8b

**Comment by onyxfish** [comment]
@brianboyer This is a little rough, but wanna let me know if you disagree with any of it?

**Comment by brianboyer** [comment]
added a few comments

**Comment by onyxfish** [comment]
Edits incorporated.
