### ISSUE TITLE
Pad the persistent chrome so it doesn't get cut off on a TV

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#472]

**Comment by onyxfish** [comment]
http://sdkdocs.roku.com/display/sdkdoc/Design+Guidelines#DesignGuidelines-13%C2%A0TelevisionDesignGuidelines

**Comment by whitmoyer** [comment]
Just did some testing in the studio with @eads. The current thinking is that we could cut the "Active Zone" in half to fill the monitor in the studio.

@720p 32px left/right margin + 18px top/bottom margin

https://www.dropbox.com/s/l103omtw4gzmw71/board-overscan.png?dl=0

**Comment by onyxfish** [comment]
@dannydb Let's chat about how to implement this. It's gonna be tricky.
