### ISSUE TITLE
Sketching: mobile controls

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#489]

**Comment by whitmoyer** [comment]
What does this mean?

**Comment by onyxfish** [comment]
How does the interactivity work on a mobile device

**Comment by onyxfish** [comment]
(Changing state, muting, etc.)

**Comment by whitmoyer** [comment]
I'm not 100% on needing a Menu label. Ideally you could tap anywhere on the screen and get the menu. https://drive.google.com/open?id=0ByZKCR_Z52bdNERHY1hRekJBOGc&authuser=1
