### ISSUE TITLE
How should we display runoffs in call cards / other slides?

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#507]

**Comment by brianboyer** [comment]
We should have something like "RUNOFF" in the column where we put the +1

Or maybe, do it on two lines, like an icon:

RUN
OFF

**Comment by whitmoyer** [comment]
Here's what I came up with. 
![screenshot 2014-10-22 16 32 13](https://cloud.githubusercontent.com/assets/622410/4743754/a2b8d636-5a2a-11e4-855a-b845f5976ca3.png)

**Comment by whitmoyer** [comment]
<svg version="1.1"
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/"
     x="0px" y="0px" width="34px" height="28.4px" viewBox="0 0 34 28.4" enable-background="new 0 0 34 28.4" xml:space="preserve">
<defs>
</defs>
<g>
    <g>
        <path fill="#F39F00" d="M3.2,13H0V0h4.5c2.2,0,4.7,0.5,4.7,4.1v0.3c0,2.1-0.9,3.2-2,3.7l2,4.9H5.8L4.1,8.6H3.2V13z M4.6,5.8
            C5.2,5.8,6,5.6,6,4.3V4.2C6,3,5.2,2.7,4.6,2.7H3.2v3.1H4.6z"/>
        <path fill="#F39F00" d="M11.5,8.9V0h3.2v8.8c0,1,0.3,1.7,1.7,1.7c1.4,0,1.7-0.7,1.7-1.7V0h3.2v8.9c0,2.7-1.1,4.4-4.8,4.4
            C12.6,13.3,11.5,11.6,11.5,8.9z"/>
        <path fill="#F39F00" d="M34,13h-3.3l-3.6-7.2l0.1,2.5V13h-3V0h3.3l3.6,7.2L31,4.7V0h3V13z"/>
        <path fill="#F39F00" d="M1.7,22v-0.7c0-4.5,1.6-6.4,5.1-6.4c3.5,0,5.1,1.9,5.1,6.4V22c0,4.5-1.6,6.4-5.1,6.4
            C3.3,28.4,1.7,26.5,1.7,22z M6.9,25.7c1.5,0,1.8-1.4,1.8-3.7v-0.7c0-2.3-0.3-3.7-1.8-3.7H6.7c-1.5,0-1.8,1.4-1.8,3.7V22
            c0,2.3,0.3,3.7,1.8,3.7H6.9z"/>
        <path fill="#F39F00" d="M21.8,15.1v2.7h-5v2.3H21v2.7h-4.2v5.3h-3.2v-13H21.8z"/>
        <path fill="#F39F00" d="M31.9,15.1v2.7h-5v2.3H31v2.7h-4.2v5.3h-3.2v-13H31.9z"/>
    </g>
</g>
</svg>

**Comment by brianboyer** [comment]
Love it A+ go go go
