### ISSUE TITLE
Write copy for Chromecast app

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#511]
Name
Title (for store) 
Description (for store)
Icon (for store, 512x512)

**Comment by brianboyer** [comment]
I don't know the difference between Name and Title, please advise @onyxfish 

Election results and news, NPR-style, streaming on your Chromecast.

![chromecast promo](https://cloud.githubusercontent.com/assets/68644/4815229/27b1cee8-5ed5-11e4-89e1-d1d5266589f4.png)

**Comment by onyxfish** [comment]
I believe "name" is never displayed to the end user, but we can probably just make it the same as "Title" to prevent problems later.

**Comment by brianboyer** [comment]
Name: Election Party!
Title: Election Party!

**Comment by brianboyer** [comment]
crap no.

NPR Election Party!
NPR Election Party!

**Comment by onyxfish** [comment]
@xtinarees Can you please also cut a an image for this to replace the one above? Thanks!

(Then upload it here and assign it back to me.)

**Comment by xtinarees** [comment]
![chromecast-02](https://cloud.githubusercontent.com/assets/6852913/4852681/9262e15a-607e-11e4-85c2-fefed843b1c2.png)
