### ISSUE TITLE
Add display logic for uncontested races

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#526]
E.g. the Alabama senate race

**Comment by onyxfish** [comment]
Not sure I understand this ticket--can we add some more detail?

**Comment by eads** [comment]
Here's what the board currently looks like for an uncontested race:

![screen shot 2014-10-15 at 10 48 34 am](https://cloud.githubusercontent.com/assets/634572/4647308/67ae0c56-547a-11e4-8dad-da82c906e572.png)

Evie suggested we might want to indicate in the empty space that the race is uncontested.

**Comment by onyxfish** [comment]
Yep, should say uncontested.
