### ISSUE TITLE
Polish up chromecast UI

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#532]
![Sketch](https://www.dropbox.com/s/sfs3nbthroax0ky/11.png)

(https://github.com/nprapps/elections14/issues/451#issuecomment-59073740)

**Comment by onyxfish** [comment]
You can see this locally for styling by using: `http://localhost:8000/?fakecast`

**Comment by alykat** [comment]
Comp:
https://www.dropbox.com/sh/3qcs23wsvd5rz1a/AAB3P0ij2gh11HLVC0j83mDXa?dl=0#lh:null-10.png
