### ISSUE TITLE
Force slide content to fit inside slide container

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#536]
Big boards are still breaking it

**Comment by TylerFisher** [comment]
Currently forcing overflow on the stack to hide so there aren't scrollbars. Moving everything to vws/vmins as @xtinarees is doing on the big boards will be the real fix.

**Comment by onyxfish** [comment]
Marking blocked for the moment since we're waiting

**Comment by onyxfish** [comment]
How are we handling this since big board vmin stuff fell apart? @xtinarees ?

**Comment by onyxfish** [comment]
Done, unless browser is wider than 16:9, in which case it scrolls. (C'est la vie)
