### ISSUE TITLE
AP results daemon doesn't appear to push to S3

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#546]
Need to add this part

**Comment by TylerFisher** [comment]
https://github.com/nprapps/elections14/blob/312902386bc03745489e729ddb701d551bc7ce0f/fabfile/daemons.py#L44-L45 These should be the deploy functions, not the render.

**Comment by eads** [comment]
Whoops! I didn't understand what was happening.

**Comment by eads** [comment]
What deploy functions should be called here?

**Comment by eads** [comment]
Fixed in a0ef684
