### ISSUE TITLE
Implement design updates to Big Board

### ISSUE THREAD

**Issue by whitmoyer** [nprapps/elections14#549]
This screenshot with notations includes:
1. States are now the first default column and the pickups will be paired with them
2. The incumbent indicator is a few notches larger
3. There's more spacing in between the two candidates
4. An Independent candidate has been included

https://www.evernote.com/shard/s116/sh/5fcb77b3-13c3-47cd-946f-81dda8450a84/58fa7e2fd342e547d73a96ab4d54e6a0

**Comment by dannydb** [comment]
This is done except maybe the incumbent indicator, which has its own ticket (#663).
