### ISSUE TITLE
Research push vendors

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#55]

**Comment by TylerFisher** [comment]
@eads and I sent emails to Firebase and Pusher (PubHub was the only other decent-looking service we found) about short-term enterprise plans.

**Comment by eads** [comment]
A couple other seemingly respectable options:
- https://www.hydna.com/ - Swedish version of Firebase et al, seem about on par 
- https://fanout.io/ - A push CDN... the pricing model fits our use case very nicely -- there's only one plan, a $25/month subscription and you pay by the message/minute of connection time.

**Comment by onyxfish** [comment]
Possible read solutions:
- Pusher
- PubNub
- Firebase
- Hydna
- S3 polling
- RDS w/ proxy

Possible write solutions:
- Firebase
- Hydna
- RDS w/ proxy
- Elasticsearch w/ proxy

**Comment by eads** [comment]
Talked with pubnub, they would be a viable write solution as well.

**Comment by onyxfish** [comment]
Pretty sure we've decided to handle results with polling, rather than push. For the game side we've basically reduced the list to Firebase and RDS. Hydna was miscategorized as write solution--it only handles push.
