### ISSUE TITLE
Getting big board slides working is a little funky 

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#561]
I have to run

```
fab data.bootstrap data.mock_slides render.render_big_boards
```

Am I doing something wrong? @onyxfish @TylerFisher

**Comment by TylerFisher** [comment]
Do you have to rebootstrap every time?

**Comment by eads** [comment]
Good point, no. But mock_slides seems a requirement to running render_big_boards

**Comment by TylerFisher** [comment]
If the slide is already in the DB, you shouldn't need to?

**Comment by onyxfish** [comment]
Is this a real issue or should we close it?
