### ISSUE TITLE
Pull an appropriate image size for tumblr photo slides

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#569]
We're just using the biggest one:

https://github.com/nprapps/elections14/blob/master/fabfile/liveblog.py#L84

**Comment by TylerFisher** [comment]
Welllllll

This is done on the server side. How do we know what the "appropriate" size is for the user? I'd imagine it's also a little dependent on the photo that's uploaded to Tumblr.

**Comment by onyxfish** [comment]
Pick one size thats big enough. But not the biggest one if that ones too huge.
