### ISSUE TITLE
Style up state results card to match mockup

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#574]
https://www.dropbox.com/sh/3qcs23wsvd5rz1a/AAB3P0ij2gh11HLVC0j83mDXa?dl=0#lh:null-10.png

Blocked by #573.

**Comment by eads** [comment]
Unblocked -- there are now "state_senate.html" and "state_house.html" templates for senate+gov and house state slides. They have the correct data as specified in the mockups, and look like crap!
