### ISSUE TITLE
Cooper Hewitt font weights aren't properly loading in share images

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#587]
![senate-big-board 2](https://cloud.githubusercontent.com/assets/1077075/4668291/1f2dde26-5564-11e4-8e29-f45e464f75ba.png)

**Comment by TylerFisher** [comment]
Not positive there's a way around this.

(Though it might be worth testing the master head of [phantomjs 2.0](https://github.com/ariya/phantomjs/wiki/PhantomJS-2), which claims to have solved these problems.)

**Comment by onyxfish** [comment]
No more phantom.
