### ISSUE TITLE
Figure out where our live audio feed is coming from

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#60]

**Comment by onyxfish** [comment]
Look at how we did this in 2012... though that is necessarily how we want/can do it this time.

**Comment by TylerFisher** [comment]
Got a link for the live mp3 audio stream that npr.org uses.

I threw it into our Wolves jPlayer setup locally, tested IE9+, Chrome/Safari/FF on Mac, and Chrome iOS + Safari, worked everywhere.

I'll email onlineproduction tomorrow and see if that's something we can use on election night.

**Comment by TylerFisher** [comment]
Email out.
