### ISSUE TITLE
Chromecast menu design tweaks

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#613]

**Comment by onyxfish** [comment]
Reassigning this to @brianboyer so he can tell me if he likes what we have now.

**Comment by brianboyer** [comment]
![screen shot 2014-10-28 at 11 58 57 am](https://cloud.githubusercontent.com/assets/68644/4811694/136f5496-5ebc-11e4-9372-56d4384051f5.png)

**Comment by brianboyer** [comment]
reassigning to @onyxfish for reassignment

**Comment by alykat** [comment]
Done in 6b6313271f3e5586761bf531df0d5b58105622f8. Remember to test #993
