### ISSUE TITLE
Style up "please rotate your phone" prompt

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#614]
This should probably take over the screen

**Comment by alykat** [comment]
Related:
https://github.com/nprapps/elections14/issues/488
https://docs.google.com/a/npr.org/file/d/0ByZKCR_Z52bddkdaa3V1TDhfZ00/edit

**Comment by alykat** [comment]
Mocked it up more or less according to Nick's comp, which isn't a screen takeover — just a message at the bottom with an icon. You can still use the site in portrait mode — it's just a sub-optimal experience. Let's talk about pros/cons of that tomorrow.

**Comment by alykat** [comment]
Leaving as is after talking w/ Brian and Chris.
