### ISSUE TITLE
Analytics: Track what state users choose

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#624]
would love to know if people stick around in a state w/ no races, or if there's only some types of races, etc. are we tracking the state people pick?

**Comment by onyxfish** [comment]
Nothing is being tracked yet, but this seems right.

Related to #350.

**Comment by onyxfish** [comment]
@TylerFisher I crown you king of analytics. Let's chat about it.

**Comment by TylerFisher** [comment]
Got this
