### ISSUE TITLE
Test slide time defaults

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#629]

**Comment by TylerFisher** [comment]
How and with who?

**Comment by onyxfish** [comment]
Grab some random folks? I bet @beckylettenberger would have some good suggestions.

**Comment by beckylettenberger** [comment]
Happy to help with whatever you guys need!

**Comment by onyxfish** [comment]
Amita was onboard. Should find some random folks to test with, but need good test data first.
