### ISSUE TITLE
Write docs for creating share images

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#648]

**Comment by onyxfish** [comment]
Firefox responsive design tool + preset 720x480 size + ?share urls === profit

**Comment by onyxfish** [comment]
Put these in a Google Doc in the elections14 folder. Screenshots would be super helpful.

**Comment by TylerFisher** [comment]
Rough draft: https://docs.google.com/a/tylerjfisher.com/document/d/1oqozfc-lqhTEJlrI7hUb_JlXsNv5BQH4JgK5nYWyokg/edit#

**Comment by TylerFisher** [comment]
Done https://docs.google.com/a/tylerjfisher.com/document/d/1oqozfc-lqhTEJlrI7hUb_JlXsNv5BQH4JgK5nYWyokg/edit#
