### ISSUE TITLE
Chrome design updates

### ISSUE THREAD

**Issue by whitmoyer** [nprapps/elections14#698]
1. Use Geomicons icons in 
   ![elections_2014](https://cloud.githubusercontent.com/assets/622410/4728149/cf31e65c-5972-11e4-86ad-a4b7c72cef90.png)
   Chrome

**Comment by whitmoyer** [comment]
1. Vertically align #hashtag 
2. Senate w/initial caps and drop the word "Results"
3. Use Gotham
   ![elections_2014](https://cloud.githubusercontent.com/assets/622410/4728192/71e72970-5973-11e4-8faf-262c6dadce76.png)

**Comment by whitmoyer** [comment]
1. Remove solid background color on Chrome 
   ![elections_2014](https://cloud.githubusercontent.com/assets/622410/4728216/acb4c062-5973-11e4-89a3-9ec77e556b5c.png)

**Comment by xtinarees** [comment]
"remove solid background color on chrome" issue actually image on slide not expanding to header area

**Comment by whitmoyer** [comment]
Yeah, I think we need to have the header area overlay on top of the slides.
