### ISSUE TITLE
Draft launch timeline/schedule

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#707]

**Comment by onyxfish** [comment]
Doc stubbed here: https://docs.google.com/document/d/1V-Y0Ej0l5V-8itm-xy4BrOLytcOpbGdETsAZdIrwlrI/edit#
Follow pattern from this: https://docs.google.com/document/d/19Z36610FhLuzWE_itlPuMSd4OdO8gZ6ICtRJgy-hp_8/edit#heading=h.xgdmaasw5puc

**Comment by onyxfish** [comment]
First draft done.

**Comment by brianboyer** [comment]
coolio. what i'd like to see is a timeline/checklist for promotion on election day, and during our coverage
