### ISSUE TITLE
Get AP vote count / calls test data

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#72]
General election tests don't start until October 6th. Can we get sample JSON responses before then?

**Comment by onyxfish** [comment]
If we can't get test data then let's mock up our clean data and build everything from there to the client. We can build the AP -> clean step later if need be.

**Comment by eads** [comment]
There is a sample response in the docs. It's for a primary, but could be
adjusted to create a first pass at consuming the diff data.

On Tue, Sep 9, 2014 at 3:55 PM, Christopher Groskopf <
notifications@github.com> wrote:

> If we can't get test data then let's mock up our clean data and build
> everything from there to the client. We can build the AP -> clean step
> later if need be.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nprapps/elections14/issues/72#issuecomment-55023910.

## 

David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by TylerFisher** [comment]
Created a fake json response here https://github.com/nprapps/elections14/blob/master/fake.json
