### ISSUE TITLE
Design chromecast prompt for welcome screen

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#731]

**Comment by onyxfish** [comment]
Should probably show cast button in Chrome and Chromecast badger everywhere else

**Comment by whitmoyer** [comment]
![1](https://cloud.githubusercontent.com/assets/622410/4745264/53b44f76-5a38-11e4-86a7-b289b293430d.png)
![15](https://cloud.githubusercontent.com/assets/622410/4745266/57b72846-5a38-11e4-883f-e3e2cb55617a.png)
