### ISSUE TITLE
When adblock is enabled, and geoip fails, everything doesn't work

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#735]

**Comment by onyxfish** [comment]
On staging

**Comment by onyxfish** [comment]
Make this failsafe

**Comment by TylerFisher** [comment]
Can't replicate

**Comment by onyxfish** [comment]
This is def still happening. Firefox Private window + Adblock Plus = broken.

**Comment by onyxfish** [comment]
@TylerFisher Take another look at this? Replicated on the first try for me. Make sure you're in a fresh private window so there no lingering cookies.

**Comment by TylerFisher** [comment]
Still can't replicate

**Comment by onyxfish** [comment]
Haha! I haz idea. Remove the geoip include. Watch everything break. Fix it. Assign back to me so I can verify it fixed my issue. :)  Magic!

**Comment by TylerFisher** [comment]
Try it now 2c88c15ec35b9baed4ba3b5020e80463b7df96a9
