### ISSUE TITLE
We need some kind of indicator or clue that this stuff is gonna rotate and you're gonna have to wait

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#740]
maybe we always start the stack with something short

but also i feel like a countdown or something that moves and shows progress... 

0:20
0:19
0:18

1/23
2/23
3/23

maybe?

I dont know what this is but you really don't know what to do after you hit "go"

**Comment by onyxfish** [comment]
@nickwhitmoyer Want to sketch some ideas for this and @TylerFisher or I can implement?

**Comment by whitmoyer** [comment]
Originally I was thinking something like this on the Go button would be cool with a countdown inside of it. Sounds like a pattern we could create and reuse. http://codepen.io/grayghostvisuals/pen/chmgK

**Comment by whitmoyer** [comment]
Here are some more loaders http://codepen.io/collection/jifIK/

**Comment by whitmoyer** [comment]
I dig this http://codepen.io/rglazebrook/pen/bcqhe

**Comment by alykat** [comment]
NYT uses a nice little rotate symbol + countdown timer. Screenshot from 2012:

![image](https://cloud.githubusercontent.com/assets/491318/4762369/336950e4-5b01-11e4-9694-070cf2834046.png)

**Comment by alykat** [comment]
WaPo did something similar in 2012:

![image](https://cloud.githubusercontent.com/assets/491318/4762377/555d651e-5b01-11e4-88e7-c128237c078f.png)

**Comment by whitmoyer** [comment]
Nice! Thanks for the point of reference. I'll push on this tomorrow morning.

On Thu, Oct 23, 2014 at 6:10 PM, Alyson Hurt notifications@github.com
wrote:

> WaPo did something similar in 2012:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/491318/4762377/555d651e-5b01-11e4-88e7-c128237c078f.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/nprapps/elections14/issues/740#issuecomment-60317489.

## 

Nick Whitmoyer
@whistle http://twitter.com/whistle

**Comment by alykat** [comment]
Done in b9d526eec8ecf10cc07be029f83e2e2c658ea1da
