### ISSUE TITLE
JSON files sent to client need to be smaller

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#77]
Reducing to races we care about and gzipping will help some, but probably need other ways to reduce them

**Comment by eads** [comment]
This gets at some of my architectural questions. Are we thinking of using a
channel to push results to the client? That would obviate this concern, I
would think.

**Comment by onyxfish** [comment]
Yeah, if we got the push route this will resolve itself.

**Comment by onyxfish** [comment]
No longer an issue since we're rerendering the pages.
