### ISSUE TITLE
The BOP in the header never gets updated

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#782]
Ha

**Comment by onyxfish** [comment]
SOooooo, we write a JSON file that the client pings for.

Maybe #680 can piggyback on this? Maybe?

**Comment by onyxfish** [comment]
That BOP should become a JSON template... or we use data-attributes? One or the other.

**Comment by onyxfish** [comment]
I don't see in this commit where the JSON file is actually getting deployed?

**Comment by TylerFisher** [comment]
Working. See 8117db1ba20c0d912fb5f44f5435a46cf60c82ca and daa9e58bd29df28e8ba494e6adb377d903ec4403
