### ISSUE TITLE
Firefox unicode arrow not rendering on the BOP chart

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#795]
FF, OSX

![screen shot 2014-10-23 at 6 17 49 pm](https://cloud.githubusercontent.com/assets/33046/4763037/e2a38e86-5b0a-11e4-9ca4-dc416d95bd5c.png)

**Comment by alykat** [comment]
Huh! It's supposed to be a little arrow. Looks like this in Chrome:

![image](https://cloud.githubusercontent.com/assets/491318/4770034/34000036-5b81-11e4-9bad-b4268b9bd73d.png)

**Comment by onyxfish** [comment]
Tweaked ticket title to be specific that it's a FF bug.
