### ISSUE TITLE
Does uncontested need additional styling?

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#801]
@alykat @dannydb @xtinarees thoughts?

![screen shot 2014-10-24 at 9 42 57 am](https://cloud.githubusercontent.com/assets/634572/4770263/e3bff042-5b83-11e4-8b3e-16d3ac0e5200.png)

**Comment by onyxfish** [comment]
I think this looks good, let's let Brian critique it when he does his fine-tooth edit.
