### ISSUE TITLE
House h1 makes BOP drop to second line on my screen

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#805]
![screen shot 2014-10-24 at 10 23 04 am](https://cloud.githubusercontent.com/assets/634572/4770899/864fb2fc-5b89-11e4-922b-67836501e8e2.png)

**Comment by alykat** [comment]
I wonder if "PAGE 1 OF 2" should be smaller / less bold.

**Comment by dannydb** [comment]
@eads: You’re missing some styles and template updates. It’s supposed to look like this:

![screen shot 2014-10-27 at 9 27 35 am](https://cloud.githubusercontent.com/assets/419297/4791433/1503d9e2-5ddd-11e4-871a-f770e0f35048.png)
