### ISSUE TITLE
At small breakpoints, invitation button truncates breadly

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#820]
![screen shot 2014-10-24 at 3 30 09 pm](https://cloud.githubusercontent.com/assets/33046/4775927/cc6e748e-5bbc-11e4-9d12-0f5143ca5479.png)

**Comment by dannydb** [comment]
not sure how to reproduce this

![screen shot 2014-10-24 at 4 51 50 pm](https://cloud.githubusercontent.com/assets/419297/4776214/9cc70dc4-5bbf-11e4-93a3-b88d90686916.png)

**Comment by onyxfish** [comment]
That's fine. I was scaling the browser way down on my desktop. If it looks good on iphone I don't care.
