### ISSUE TITLE
Header BOP tweaks

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#827]
- Too washed out
- Too small
- "Senate results" -> "Senate"
- Use Gotham

**Comment by dannydb** [comment]
I’m conflicted about switching BOP to Gotham. I like the consistency of using Cooper for all stats.

On the other hand, these both look good to me. It’s not immediately clear which seems more readable.

![screen shot 2014-10-24 at 5 56 27 pm](https://cloud.githubusercontent.com/assets/419297/4777012/1ac33262-5bc9-11e4-8356-ebc712b560bb.png)
![screen shot 2014-10-24 at 5 57 24 pm](https://cloud.githubusercontent.com/assets/419297/4777014/1c4815b2-5bc9-11e4-985c-be37b90ae2cc.png)

**Comment by dannydb** [comment]
Curious what @alykat thinks about this one.

**Comment by alykat** [comment]
I like using Cooper Hewitt for stats-type things, and Gotham for headers / body text. (At least, that's the pattern I've been following for the scorecard slides!)

**Comment by dannydb** [comment]
Cool. That was my feeling as well. Thanks!
