### ISSUE TITLE
Fonts on the senate big board is way too small

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#829]
It didn't work on the screen in the studio

/via @nickwhitmoyer

**Comment by onyxfish** [comment]
Let's test with hosts before we close this.

**Comment by dannydb** [comment]
Fair enough. 

Be advised that going any larger than the change committed in 20e96f91760904d754811aeee77a87d96beeb9ef will push the board out of our 16x9 aspect ratio unless we reduce vertical padding in the cells and/or find other vertical space to reclaim.

**Comment by onyxfish** [comment]
Reassigning to @eads. Let's check this with during rehearsal tomorrow?
