### ISSUE TITLE
Talk to Charlie about crediting the AP

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#834]

**Comment by alykat** [comment]
Option: Put a credit line at the bottom of each screen that has results, like on the BOP graphic?

**Comment by onyxfish** [comment]
Two questions:
- Should we credit the data on every slide?
- Should we differentiate our calls from AP calls: "Called by the AP." "Called by NPR."

**Comment by eads** [comment]
We don't need to differentiate calls.

Big boards should have an AP source line. For the other slides, Charlie thinks we're doing enough of the heavy lifting that we don't need a credit line.
