### ISSUE TITLE
Incumbents slide: Display accurate totals

### ISSUE THREAD

**Issue by alykat** [nprapps/elections14#836]
![image](https://cloud.githubusercontent.com/assets/491318/4786405/c99849be-5d93-11e4-8af3-26e663f9b861.png)

Right now using hard-coded values

**Comment by onyxfish** [comment]
@TylerFisher, can you plug in the data @alykat needs for this?

**Comment by TylerFisher** [comment]
Not getting incumbency data out of AP. Blocked for now.
