### ISSUE TITLE
Why are all races 50% in on a fresh bootstrap on staging?

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#859]
![screen shot 2014-10-27 at 2 52 01 pm](https://cloud.githubusercontent.com/assets/1077075/4797265/4ceba4e8-5e0a-11e4-9ad6-fbf6d6c62416.png)

**Comment by TylerFisher** [comment]
Also, there are results? Is something not getting reset?

**Comment by TylerFisher** [comment]
Things are getting into the db with exactly 50%. Not a baking error.

**Comment by onyxfish** [comment]
Probably a red herring, need to test one more time.
