### ISSUE TITLE
House big boards should say "Selected House Races"

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#864]
Or something

**Comment by brianboyer** [comment]
We've been using "races we're watching" -- gives the behind-the-scenes feel, and evokes that it's a shortened list.

maybe:
HOUSE (big)
races we're watching (small)

**Comment by onyxfish** [comment]
Can we make this fit without pushing the races outside the frame?

**Comment by alykat** [comment]
![image](https://cloud.githubusercontent.com/assets/491318/4828162/22d57f88-5f7e-11e4-84c8-a4be47fe1275.png)

With that extra line, the House board is about the same height as the Senate board.
