### ISSUE TITLE
Implement Brian's promo edits

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#867]
![screen shot 2014-10-27 at 6 57 04 pm](https://cloud.githubusercontent.com/assets/33046/4807827/37f1e3e2-5e99-11e4-93bb-c639d1b44d6d.png)
![screen shot 2014-10-27 at 7 14 10 pm](https://cloud.githubusercontent.com/assets/33046/4807829/3e939aba-5e99-11e4-80a0-4c2b19ff2f87.png)

**Comment by dannydb** [comment]
Assuming I’m taking content and line break edits only and not font changes. Is that correct?

**Comment by dannydb** [comment]
![screen shot 2014-10-28 at 10 08 26 am](https://cloud.githubusercontent.com/assets/419297/4809458/ee95c0de-5eab-11e4-9948-18beed36ee73.png)
?

**Comment by dannydb** [comment]
@brianboyer 
![localhost8000promo-full](https://cloud.githubusercontent.com/assets/419297/4810317/79958614-5eb2-11e4-8920-214ee552a4bf.png)
