### ISSUE TITLE
State slides are interesting at different times of the night

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#899]
Currently watching the FL slide. Nothing's going to change about that after the first poll closing time. But CA wouldn't be interesting until the end of the night. Is there anything we can do about this?

**Comment by alykat** [comment]
Would it be worth adding the poll closing time to the slide, like under the state name / outline, to at least signal when to expect information?

To get super-fancy, you could hold off allowing particular states into the rotation until polls have closed there.

**Comment by TylerFisher** [comment]
Yeah, I was thinking the second. Just make the lists in app_config and query the lists on the client, skip if not interesting.

**Comment by onyxfish** [comment]
Bumping this out of the milestone. We'll talk about it if we run out of stuff to do.
