### ISSUE TITLE
Seeing unicode cruft in FF

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#928]
![screen shot 2014-10-28 at 12 27 52 pm](https://cloud.githubusercontent.com/assets/33046/4812274/6e72e8fa-5ebf-11e4-943c-120f7877392e.png)

**Comment by onyxfish** [comment]
This was from something I pasted from Mail into a Tumblr post, but Amita did not see the cruft.

**Comment by TylerFisher** [comment]
Hm. Struggling to replicate.

**Comment by TylerFisher** [comment]
Couldn't replicate
