### ISSUE TITLE
Someone double check Tyler's work compiling which states should be skipped

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#956]
See https://github.com/nprapps/elections14/blob/master/app_config.py#L202-L204

**Comment by onyxfish** [comment]
@TylerFisher Did you generate this list with code or by hand?

**Comment by TylerFisher** [comment]
Wrote SQL queries to find the matches, but then typed by hand

**Comment by onyxfish** [comment]
```
select distinct state_postal from race where office_name = 'U.S. Senate' or office_name = 'Governor' order by state_postal asc;
```

I see missing: 
DC
IN
MH
MO
ND
WA
