### ISSUE TITLE
State Picker: What if the user is outside the US?

### ISSUE THREAD

**Issue by alykat** [nprapps/elections14#960]
Don't show it? Show a different message?

**Comment by onyxfish** [comment]
It should still prompt to pick a state. Should behave as it does for users who have geoip blocked. @TylerFisher Please verify this is what currently happens.

**Comment by TylerFisher** [comment]
Works as expected, though we should now change the header when geoip fails:

![screen shot 2014-10-29 at 3 46 38 pm](https://cloud.githubusercontent.com/assets/1077075/4833391/53feb0b8-5fa4-11e4-8ac6-cabf4cf60ed9.png)
