### ISSUE TITLE
Tweak recently called slide design so we can fit 5-10 races

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#964]
Also, A. Grimes shouldn't wrap!

![screen shot 2014-10-29 at 12 27 02 pm](https://cloud.githubusercontent.com/assets/33046/4829644/73ce0248-5f88-11e4-8d9e-8a30941784b1.png)

**Comment by dannydb** [comment]
Test data is making this tough at the moment, and running the data playback doesn’t seem to make a difference.

![screen shot 2014-10-29 at 4 56 55 pm](https://cloud.githubusercontent.com/assets/419297/4834490/3f1e3510-5fae-11e4-8155-c68dda64e476.png)

Any suggestions on how to workaround? /cc @onyxfish @eads @TylerFisher
