### ISSUE TITLE
State results slide has old legend layout and its busted

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#965]

**Comment by alykat** [comment]
Weird thing: I see the new legend when I look at the state results page locally.

![image](https://cloud.githubusercontent.com/assets/491318/4832415/ff518d7c-5f9b-11e4-885f-0e519d19a2b1.png)

![image](https://cloud.githubusercontent.com/assets/491318/4832426/0e7c773a-5f9c-11e4-9a0c-e6c7da34537a.png)

**Comment by TylerFisher** [comment]
Seems like state pages are not rendering correctly.

https://d3dhid83frmf6i.cloudfront.net/preview/state-senate-results-VA/index.html

**Comment by TylerFisher** [comment]
Fixed.
