### ISSUE TITLE
Do we still want to cram share buttons in the chrome?

### ISSUE THREAD

**Issue by dannydb** [nprapps/elections14#994]
Getting tight down there…

![screen shot 2014-10-29 at 4 43 45 pm](https://cloud.githubusercontent.com/assets/419297/4834295/5a23f252-5fac-11e4-96e9-258f28ed6d23.png)

**Comment by brianboyer** [comment]
@dannydb I've got an idea about a different place for the directional controls, may free up some space.

**Comment by brianboyer** [comment]
yes. dammit. i think we do.
